### ISSUE TITLE
for async client and server, possible to give an explanation on how does it work?

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/shmipc-go#11]
for async client and server, possible to give an explanation on how does it work?

data received or transferred will be out of sync?

**Comment by goodbye-babyer** [comment]
Later this week, I will add a README to explain

**Comment by beaquant** [comment]
speedup

**Comment by goodbye-babyer** [comment]
@kolinfluence Please refer to the annotation for this interface. https://github.com/cloudwego/shmipc-go/blob/main/stream.go#L50
