### ISSUE TITLE
why does net_server and net_client with lesser code has lower QPS than shmipc_server and shmipc_client?

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/shmipc-go#12]
why does net_server and net_client with lesser code has lower QPS than shmipc_server and shmipc_client?

possible to provide example to better understand the example folder?

getting 400000 QPS with shmipc_ example and 140000 QPS with net_ example

**Comment by goodbye-babyer** [comment]
Later this week, I will add a README to explain

**Comment by kolinfluence** [comment]
@goodbye-babyer waiting for this. pls inform in this post if updated in README / doc. thx

**Comment by goodbye-babyer** [comment]
I'm sorry, I have been busy lately. Perhaps you can learn about the implementation principle of shmipc through this.
https://github.com/cloudwego/shmipc-spec
