### ISSUE TITLE
pls provide the server specifications for the shmipc-go benchmark on front page. thx

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/shmipc-go#27]
pls provide the server specifications for the shmipc-go benchmark on front page. thx

**Comment by goodbye-babyer** [comment]
emm maybe you could run example/best_pratise's cases or contribute the code :)

**Comment by kolinfluence** [comment]
@goodbye-babyer

looking forward to shmipc c++ version which is compatible with shmipc-go.

thx!
