### ISSUE TITLE
Getting shared memory exhausted, saw shmipc specification but can't find examples on how to use fallback to use uds / tcp

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/shmipc-go#29]
Getting shared memory exhausted, saw shmipc specification but can't find examples on how to use fallback to use uds / tcp

1. possible to give more details on how to use uds (and also tcp) for the fallback when shmipc is exhausted?

2. how to limit "exhaustion" of memory of shm ipc?

**Comment by goodbye-babyer** [comment]
1. When the shared memory is insufficient, it will automatically fallback to Unix domain socket. Generally, application code does not need to be concerned about it.
2. a. Through configuration, it is possible to increase the capacity of shared memory and adjust the specifications of buffer slices to better fit the application's needs.

b. Additionally, it is generally believed that shared memory is only used during data serialization and deserialization. It is allocated on the sending side and recycled on the receiving side. After the receiving side deserializes the shared memory into a "business object," it needs to explicitly call API functions to recycle the shared memory, such as BufferReader.ReleasePreviousRead or Stream.ReleaseReadAndReuse().

c. Supporting stream blocking write mechanism, but it is currently not implemented.

**Comment by kolinfluence** [comment]
@goodbye-babyer ok thx.

**Comment by kolinfluence** [comment]
@goodbye-babyer 
> a. Through configuration, it is possible to increase the capacity of shared memory and adjust the specifications of buffer slices to better fit the application's needs.

possible to advise where to set / control this setting?
i used shmipc in multiple connections almost everywhere and it's using a lot of memory. how do i limit / control it?

**Comment by goodbye-babyer** [comment]
currently, maybe you should  improve server's performance to handle more data.  And next, shmipc will provide blocking write interface in the future.

**Comment by kolinfluence** [comment]
@goodbye-babyer how do i control the memory use?

it's like using 800mb per process
these are my settings, no matter what i tried, it;s always using 800mb
how do i minimize the mb used?
```
		shmipcconf = shmipc.DefaultConfig()
		shmipcconf.QueueCap = 1
		shmipcconf.ShareMemoryBufferCap = 1 * 1024 * 1024 //must be greater than 1mb

		sessManagerConf = shmipc.DefaultSessionManagerConfig()
		sessManagerConf.Config = shmipcconf
		sessManagerConf.QueueCap = 1
		sessManagerConf.Network = "unix"
		sessManagerConf.MaxStreamNum = 1
		sessManagerConf.MemMapType = shmipc.MemMapTypeMemFd
		sessManagerConf.SessionNum = 1
		sessManagerConf.InitializeTimeout = 10 * time.Second
```

**Comment by goodbye-babyer** [comment]
@kolinfluence seems in other issuse had solved, do you have any question now?

**Comment by GuangmingLuo** [comment]
Closed as no further follow-up.
