### ISSUE TITLE
long running process where server is slow causes OOM.

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/shmipc-go#34]
attached issues. if long running processes will get this "error", which uses a lot of memory and doesnt really free up.
with cpu thrashing in the background

![screen160](https://github.com/cloudwego/shmipc-go/assets/104323920/cdc19845-7c15-4526-8941-c77c166190cd)

**Comment by kolinfluence** [comment]
it's other issues.

**Comment by goodbye-babyer** [comment]
> attached issues. if long running processes will get this "error", which uses a lot of memory and doesnt really free up. with cpu thrashing in the background
> 
> ![screen160](https://user-images.githubusercontent.com/104323920/250216275-cdc19845-7c15-4526-8941-c77c166190cd.png)

I suggest exporting a flame graph of the heap for analysis.
