### ISSUE TITLE
memory increased after long running process. is this normal?

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/shmipc-go#38]
Sending two files of heap profiles with timestamped difference. 

is this normal or is this a memory leak?

![Screenshot from 2023-08-15 19-10-36](https://github.com/cloudwego/shmipc-go/assets/104323920/8c6e620f-c0ae-46e8-a0b6-e2e69c942095)

![Screenshot from 2023-08-15 19-11-00](https://github.com/cloudwego/shmipc-go/assets/104323920/d22f32dc-dd41-4057-8049-d6a2459b609a)

**Comment by goodbye-babyer** [comment]
same as https://github.com/cloudwego/shmipc-go/issues/39
