### ISSUE TITLE
long running processes uses a lot of ram memory, how to estimate how much ram to allocate for shmipc-go?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/shmipc-go#44]
1. long running processes uses a lot of ram memory, how to estimate how much ram to allocate for shmipc-go?
2. how to do the configuration setting?

**Comment by goodbye-babyer** [comment]
@hiqsociety please give a memory flame graph  cc @zhquzzuli

**Comment by hiqsociety** [comment]
@goodbye-babyer is id needed in idl.go?

**Comment by zhquzzuli** [comment]
@hiqsociety Session manager array sessManager[cpuIDHash], whether 1st process and 2nd process has the same index cpuIDHash value.

**Comment by hiqsociety** [comment]
i used two different configurations with Default Config

sessManagerFirst[cpuIDHash] // <- this one PutBack works using first.sock

sessManagerSecond[cpuIDHash] // <- this one PutBack work first time, call GetStream and PutBack will hang on 2nd time

they are not related but in same program

**Comment by hiqsociety** [comment]
@zhquzzuli can u help verify if this is ok? i did this customized idl,
pls help check and verify if this is the correct way to use shmipc.
thx
https://pastebin.com/Yzd1wLde

**Comment by hiqsociety** [comment]
@GuangmingLuo @zhquzzuli 
any problems below with the idl i have shown?

```
	if sessManagerWebax[cpuIDHash] == nil {
 
		sessManagerWebaxConf.Address = filepath.Join(shmipcdir, "../webax"+cxstrconv.Uint16toa(cpuIDHash)+".sock")
		sessmgr, err := shmipc.NewSessionManager(sessManagerWebaxConf)
		if err != nil {
			log.Fatal("sessManagerWebax xcannot init3 = %s", err)
			return
		}
		sessManagerWebax[cpuIDHash] = sessmgr
 
	}
	stream, err := sessManagerWebax[cpuIDHash].GetStream()
	if err != nil {
		log.Println("get stream error3:" + err.Error())
		httpdisplay.CtxStatusDisplayUnavail(ctx)
		return
	}
 
	defer sessManagerWebax[cpuIDHash].PutBack(stream) //works first time, doesnt work the 2nd time. why?
	```

**Comment by hiqsociety** [comment]
@GuangmingLuo @zhquzzuli 

first pass, ok
stream data &{2 0 0xc00018aea0 0xc000112190 0xc0003cea00 0xc0003cea40 0xc000891c50 0xc00012ca80 0xc00012cae0 {0 {0 0}} {0 0 <nil>} {0 0 <nil>} <nil> false <nil> 0 {{} {{} {} 0} 0} 0}

putback(stream)

second pass, hang
2023/08/30 06:46:23 stream data &{2 0 0xc00018aea0 0xc000112190 0xc0003cea00 0xc0003cea40 0xc000891c50 0xc00012ca80 0xc00012cae0 {0 {0 0}} {0 0 <nil>} {0 0 <nil>} <nil> false 0xc0001b1520 0 {{} {{} {} 0} 0} 0}
i did log.Printf("stream data %v", stream), can ju pls check why? the next time i call GetStream, stream is "ok" again. so every 2nd time will hang. first time is ok

the new stream will have different value. 

3rd pass, ok
tream data &{3 0 0xc00018aea0 0xc000112190 0xc0003cedc0 0xc0003cee00 0xc0004c5ce0 0xc00012d020 0xc00012d080 {0 {0 0}} {0 0 <nil>} {0 0 <nil>} <nil> false <nil> 0 {{} {{} {} 0} 0} 0}


pls give comments on why. there's 0xc0001b1520 after "false" on 2nd pass after putback(stream). why does it hang?

**Comment by hiqsociety** [comment]
sorry i successfully debugged. it's "server" side issue of shmipc. thanks!

sorry about this.

it's totally new and was exploring how to get it done. i get it now. thx

**Comment by hiqsociety** [comment]
solved because i did 
```
func handleStream(...

    //for { // i commented out
        if err:=req.ReadFromShm // <- 
    
    
    //}
