### ISSUE TITLE
why NewListener only support linux?

### ISSUE THREAD

**Issue by beaquant** [cloudwego/shmipc-go#45]
why `NewListener` only support linux?
osx may be ok?

https://github.com/cloudwego/shmipc-go/blob/9f40696f4d3e529ab4c4a37fdfbec75d2fc14ff7/listener.go#L81

**Comment by Huafanfan** [comment]
I also want to ask if there are any plans to support Mac OS in the future.

**Comment by goodbye-babyer** [comment]
Runing shmipc in mac for developing? In fact, there hasn't been any optimization specifically for macOS yet. Although some modifications can make it run, its performance hasn't been thoroughly fine-tuned, and alignment with other IPC mechanisms may not provide significant value.

**Comment by GuangmingLuo** [comment]
@beaquant @Huafanfan Hi, please let us know if you are going to use it in real scenario in your company so that we can provide better support.

**Comment by beaquant** [comment]
development envriment is macOS, it can debug and trace issue. But the produce envirment is linux.

**Comment by GuangmingLuo** [comment]
@beaquant Please leave your company info and use case here : https://github.com/cloudwego/shmipc-go/issues/25

**Comment by beaquant** [comment]
enn, I develop application by myself. company doesn't setup.
Sorry

**Comment by GuangmingLuo** [comment]
> enn, I develop application by myself. company doesn't setup. Sorry

OK, thanks for your feedback. 
Based on what @goodbye-babyer has answered, this issue will be closed as not supported.
