### ISSUE TITLE
Not supported to run on Linux with ARM architecture

### ISSUE THREAD

**Issue by Huafanfan** [cloudwego/shmipc-go#46]
I run helloworld on Linux with ARM architecture. When the client sends a request, a panic occurs at position queue.go #249. I want to ask if this is a known issue? Will it be supported in the future?

**Comment by zhquzzuli** [comment]
We have supported ARM architecture, @goodbye-babyer will submit pr.

**Comment by GuangmingLuo** [comment]
@Huafanfan Hi, please let us know if you are going to use it in real scenario in your company so that we can provide better and timely support.

**Comment by Huafanfan** [comment]
@GuangmingLuo Hi, master. my development computer is mac m1, and the architecture is arm. Because mac is not currently supported, I need to run it in docker. Because m1 pulls the arm architecture image by default, an error occurred when I ran it. Now it needs to be run in the amd64 image, but the performance on the m1 chip is very poor. So I hope it can support arm

**Comment by GuangmingLuo** [comment]
> @GuangmingLuo Hi, master. my development computer is mac m1, and the architecture is arm. Because mac is not currently supported, I need to run it in docker. Because m1 pulls the arm architecture image by default, an error occurred when I ran it. Now it needs to be run in the amd64 image, but the performance on the m1 chip is very poor. So I hope it can support arm

Thanks for your reply, but please do not call me master, call my name instead. You still haven't answered my question yet.  Are going to use it in real scenario in your company (which means in production) ?  The project based on shmipc should be run in Linux env.  @Huafanfan

**Comment by Huafanfan** [comment]
@GuangmingLuo We are conducting research on this product. We are currently using UDS, but its performance is not good enough in certain scenarios. If shmipc can significantly improve performance and have good stability, it will be deployed to the production environment (Linux).

**Comment by GuangmingLuo** [comment]
@goodbye-babyer please evaluate this request to support ARM.

**Comment by maple0575** [comment]
> 我们已经支持ARM架构，将提交pr。

请问，什么时候可以支持ARM架构，已经修复了吗

**Comment by beaquant** [comment]
any update?

**Comment by GuangmingLuo** [comment]
done by https://github.com/cloudwego/shmipc-go/pull/56 , added a tag v0.2.0
