### ISSUE TITLE
how does the locking and unlocking mechanism work?

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/shmipc-go#54]
@goodbye-babyer possible to give a guide on how does the synchronization of locking and unlocking works? which .go file is it in?

**Comment by zhquzzuli** [comment]
> @goodbye-babyer possible to give a guide on how does the synchronization of locking and unlocking works? which .go file is it in?

@kolinfluence hi, this file: [queue.go](https://github.com/cloudwego/shmipc-go/blob/main/queue.go)

**Comment by kolinfluence** [comment]
@zhquzzuli thanks.
