### ISSUE TITLE
请问 Shmipc的方案在serviceMesh场景下，有和ebpf的socket redirect做过对比吗？

### ISSUE THREAD

**Issue by xj524598** [cloudwego/shmipc-go#7]
今天看了Shmipc在serviceMesh场景下，对于大包场景下做到了较好的收益。请问 Shmipc的方案在serviceMesh场景下，有和ebpf的socket redirect做过对比吗？谁更好点

**Comment by goodbye-babyer** [comment]
我晚点做个测试看看 就转发而言 直观感觉ebpf是overhead最低的 不过目前ebpf提供的编程范式做不了复杂逻辑 比如协议解析服务治理啥的 这两者感觉不在同个维度。 service mesh场景下重点在于ipc之后能做自定义逻辑， ebpf socket rediect 相当没有ipc了，也做不了ipc之后的逻辑。

**Comment by GuangmingLuo** [comment]
已与该用户沟通，没有真实落地需求，先 close。
